name: Add Question to HTML

on:
  repository_dispatch:
    types: [new-question]

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add question to HTML
      run: |
        FILE="index.html"
        QUESTION="${{ github.event.client_payload.question }}"
        ANSWER="${{ github.event.client_payload.answer }}"
        BLOCK="<details><summary>${QUESTION}</summary><p>${ANSWER}</p></details>"

        # Append it to the end of file
        echo "$BLOCK" >> $FILE

    - name: Commit and push
  env:
    GH_TOKEN: ${{ secrets.GH_PAT }}
  run: |
    git config user.name "quiz-bot"
    git config user.email "quiz-bot@users.noreply.github.com"
    git add index.html
    git commit -m "Add question: ${{ github.event.client_payload.question }}"
    git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main


